-- Schema script for the current backend models
-- Run on MySQL/MariaDB

CREATE DATABASE IF NOT EXISTS `udck` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `udck`;

-- USERS table
CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Role` ENUM('Admin','Student','Lecturer') NOT NULL,
  `Status` ENUM('Active','Locked') NOT NULL DEFAULT 'Active',
  `loginAttempts` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- STUDENT table
CREATE TABLE IF NOT EXISTS `STUDENT` (
  `Student_ID` INT NOT NULL,
  `User_ID` INT UNIQUE,
  `Major_ID` INT DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Full_Name` VARCHAR(100) NOT NULL,
  `ClassName` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`Student_ID`),
  UNIQUE KEY `UK_STUDENT_EMAIL` (`Email`),
  CONSTRAINT `FK_STUDENT_USER` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENT_MAJOR` FOREIGN KEY (`Major_ID`) REFERENCES `MAJORS` (`Major_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- LECTURER table
CREATE TABLE IF NOT EXISTS `LECTURER` (
  `Lecturer_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT UNIQUE,
  `Email` VARCHAR(100) NOT NULL,
  `Full_Name` VARCHAR(100) NOT NULL,
  `picture` TEXT DEFAULT NULL,
  `Phone` VARCHAR(20) DEFAULT NULL,
  `Academic_Rank` VARCHAR(100) DEFAULT NULL,
  `Office_Room` VARCHAR(50) DEFAULT NULL,
  `Specialization` VARCHAR(200) DEFAULT NULL,
  `Bio` TEXT DEFAULT NULL,
  `Dept_ID` INT DEFAULT NULL,
  `Major_ID` INT DEFAULT NULL,
  PRIMARY KEY (`Lecturer_ID`),
  UNIQUE KEY `UK_LECTURER_EMAIL` (`Email`),
  CONSTRAINT `FK_LECTURER_USER` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_LECTURER_DEPT` FOREIGN KEY (`Dept_ID`) REFERENCES `DEPARTMENTS` (`Dept_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_LECTURER_MAJOR` FOREIGN KEY (`Major_ID`) REFERENCES `MAJORS` (`Major_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ADMIN table
CREATE TABLE IF NOT EXISTS `ADMIN` (
  `Admin_ID` INT NOT NULL AUTO_INCREMENT,
  `Full_Name` VARCHAR(100) NOT NULL,
  `User_ID` INT UNIQUE,
  PRIMARY KEY (`Admin_ID`),
  CONSTRAINT `FK_ADMIN_USER` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DEPARTMENTS table
CREATE TABLE IF NOT EXISTS `DEPARTMENTS` (
  `Dept_ID` INT NOT NULL AUTO_INCREMENT,
  `DeptName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Dept_ID`),
  UNIQUE KEY `UK_DEPARTMENT_NAME` (`DeptName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- MAJORS table
CREATE TABLE IF NOT EXISTS `MAJORS` (
  `Major_ID` INT NOT NULL AUTO_INCREMENT,
  `Dept_ID` INT DEFAULT NULL,
  `MajorName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Major_ID`),
  UNIQUE KEY `UK_MAJOR_NAME` (`MajorName`),
  CONSTRAINT `FK_MAJOR_DEPT` FOREIGN KEY (`Dept_ID`) REFERENCES `DEPARTMENTS` (`Dept_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- AVAILABLE_SLOTS table
CREATE TABLE IF NOT EXISTS `AVAILABLE_SLOTS` (
  `Slot_ID` INT NOT NULL AUTO_INCREMENT,
  `Lecturer_ID` INT DEFAULT NULL,
  `Date` DATE NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `IsBooked` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`Slot_ID`),
  CONSTRAINT `FK_AVAILABLE_SLOTS_LECTURER` FOREIGN KEY (`Lecturer_ID`) REFERENCES `LECTURER` (`Lecturer_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- APPOINTMENTS table
CREATE TABLE IF NOT EXISTS `APPOINTMENTS` (
  `Appoint_ID` INT NOT NULL AUTO_INCREMENT,
  `Slot_ID` INT DEFAULT NULL,
  `Student_ID` INT DEFAULT NULL,
  `Lecturer_ID` INT DEFAULT NULL,
  `Location` VARCHAR(100) DEFAULT NULL,
  `StuStartTime` TIME DEFAULT NULL,
  `StuEndTime` TIME DEFAULT NULL,
  `Reason` VARCHAR(255) DEFAULT NULL,
  `Status` ENUM('Pending','Approved','Rejected','Cancelled') NOT NULL DEFAULT 'Pending',
  `RejectionReason` TEXT DEFAULT NULL,
  `CancellationReason` TEXT DEFAULT NULL,
  `AdjustedAt` DATETIME DEFAULT NULL,
  `AdjustmentNote` TEXT DEFAULT NULL,
  `RequestedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Appoint_ID`),
  CONSTRAINT `FK_APPOINTMENTS_SLOT` FOREIGN KEY (`Slot_ID`) REFERENCES `AVAILABLE_SLOTS` (`Slot_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_APPOINTMENTS_STUDENT` FOREIGN KEY (`Student_ID`) REFERENCES `STUDENT` (`Student_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_APPOINTMENTS_LECTURER` FOREIGN KEY (`Lecturer_ID`) REFERENCES `LECTURER` (`Lecturer_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_APPOINTMENTS_ADJUSTED_BY` FOREIGN KEY (`AdjustedBy`) REFERENCES `USERS` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTIFICATIONS table
CREATE TABLE IF NOT EXISTS `NOTIFICATIONS` (
  `Noti_ID` INT NOT NULL AUTO_INCREMENT,
  `Admin_ID` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Content` TEXT NOT NULL,
  `Target_Role` ENUM('Student','Lecturer','All') NOT NULL DEFAULT 'All',
  `Created_At` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Noti_ID`),
  CONSTRAINT `FK_NOTIFICATIONS_ADMIN` FOREIGN KEY (`Admin_ID`) REFERENCES `ADMIN` (`Admin_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- NOTIFICATION_READS table
CREATE TABLE IF NOT EXISTS `NOTIFICATION_READS` (
  `NotificationRead_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `NotificationKey` VARCHAR(255) NOT NULL,
  `Read` BOOLEAN NOT NULL DEFAULT FALSE,
  `Read_At` DATETIME DEFAULT NULL,
  PRIMARY KEY (`NotificationRead_ID`),
  UNIQUE KEY `UK_NOTIFICATION_READS_USER_KEY` (`User_ID`,`NotificationKey`),
  CONSTRAINT `FK_NOTIFICATION_READS_USER` FOREIGN KEY (`User_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
